# -*- coding: utf-8 -*-
"""DAY1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q0BtQL0lYANkY9rneu9o3YPQYoMdoEnd
"""

#Day 1 Assignment
# take multiple numbers as input and print the sum
# method 1

x=[int(i) for i in input ('Enter the values:').split()]
sum=0
for j in x :
  sum += j
  print(sum)

# method 2

from functools import reduce
x=[int(i)for i in input('enter integer value:').split()]
res=reduce(lambda a,b:a+b,x)
print(res)