# -*- coding: utf-8 -*-
"""DAY2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g3H4lG0Rpi_H30HjZQnwAQAaCyJeBeHB
"""

#Day 2 : Python zero to Hero
a="hello coders"
inp=input("enter a letter: ")
if inp==a[0].lower() or inp==a[1].lower() or inp==a[4].lower() or inp==a[6].lower() or inp==a[8].lower():
    print("you get the prize")
else:
    print("you are guessing is wrong")