# -*- coding: utf-8 -*-
"""DAY5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v0kPVjHS0022pE4FmKSE2l0QFIqi4N0R
"""

#Day 5 Assignment: 
#Use filter function to filter out the elements from a list that are divisible by 3 & 5

li = list(range(0,100))
result = filter(lambda x: x % 3== 0, li) #divisible by 3
print('Divisble by 3:') 
print(list(result))

result = filter(lambda x: x % 5 == 0, li) #divisible by 5
print('Divisble by 5:')
print(list(result))